language: generic
sudo: required
services:
 - docker

 before_install:
  - docker build -t oharutz/docker-react -f Dokcerfile.dev .

  script:
    - docker run -e CI=true oharutz/docker-react npm run test